### ISSUE TITLE
Add AJAX support.

### ISSUE THREAD

**Issue by ethmtrgt** [ethmtrgt/url_shortener#1]
Add AJAX support to run the app without refreshing the page.

**Comment by ashvathnarayanan** [comment]
Where should the output be after adding ajax?

**Comment by ashvathnarayanan** [comment]
I have added ajax and the output is seen the browser console. (no refresh takes place)

**Comment by ethmtrgt** [comment]
Hey @ashvathnarayanan thanks for your contribution!

You can insert an element with `card` class inside of the `#main` element.

Example: 
```html
<div id="main">
    ...
    <div class="card">
        <a href="[output_url_will_be_here]">[output_url_will_be_here]</a>
    </div>
    ...
</div>
```
