### ISSUE TITLE
Make an admin page

### ISSUE THREAD

**Issue by ethmtrgt** [ethmtrgt/url_shortener#12]
Make an admin page to display most clicked links in a page. You can use Django's default auth library and user model for authentication.

**Comment by theyup12** [comment]
can I work on this?

**Comment by ethmtrgt** [comment]
Hey @theyup12, yes you can. Thank you!

**Comment by ethmtrgt** [comment]
@theyup12 If you need any assistance, please hit me up. My email is ethmtrgt@gmail.com

**Comment by theyup12** [comment]
Hi, Can you be more detail on what do you want on the admin page?

**Comment by mtbun** [comment]
can i work on this issue?

**Comment by ethmtrgt** [comment]
Yes, you can @mtbun feel free to hit me up if you need something
