### ISSUE TITLE
Make responsive

### ISSUE THREAD

**Issue by ethmtrgt** [ethmtrgt/url_shortener#2]
Make index page responsive

**Comment by mohsin-sh** [comment]
can i do this

**Comment by ethmtrgt** [comment]
Hey @mohsin-sh, yes you can.

**Comment by mohsin-sh** [comment]
sorry I thought it is a plain vanilla js

**Comment by PranavTrip** [comment]
Please assign this to me I can work on making the project responsive

**Comment by ethmtrgt** [comment]
> Please assign this to me

Hey, you can work.

**Comment by GrbavaCigla** [comment]
I didn't see this was assigned...

**Comment by ethmtrgt** [comment]
> I didn't see this was assigned...

Not problem, @PranavTrip already removed his assignment.
