### ISSUE TITLE
Feature: Make the project more contributor friendly

### ISSUE THREAD

**Issue by orama254** [ethmtrgt/url_shortener#5]
Greetings @ethmtrgt 

as per Github's recommended community standards, the project seems to be missing some items on the checklist namely

- [x]  Code of conduct #10 
- [x] Contributing guidelines #9 
- [x] License #8 

#### screenshot
![ethmtrgt-url-short](https://user-images.githubusercontent.com/50571688/135816526-c3ccf5e7-dda2-4d61-93e7-6621b3fba2e6.jpg)
:
 
I'd be happy to add them to the project if you need any assistance with this

**Comment by ethmtrgt** [comment]
Hey @orama254!

I would be very grateful if you could take the time for this.

Thank you!

**Comment by orama254** [comment]
> Hey @orama254!
> 
> I would be very grateful if you could take the time for this.
> 
> Thank you!

Cool...working on it asap 👍

**Comment by orama254** [comment]
> Greetings @ethmtrgt
> 
> as per Github's recommended community standards, the project seems to be missing some items on the checklist namely
> 
> * [x]   Code of conduct [feat(#5): Add code of conduct to the project #10](https://github.com/ethmtrgt/url_shortener/pull/10)
> * [x]  Contributing guidelines [feat(#5): Add contributing.md to the project #9](https://github.com/ethmtrgt/url_shortener/pull/9)
> * [x]  License [feat(#5): Add license to the project #8](https://github.com/ethmtrgt/url_shortener/pull/8)
> 
> #### screenshot
> ![ethmtrgt-url-short](https://user-images.githubusercontent.com/50571688/135816526-c3ccf5e7-dda2-4d61-93e7-6621b3fba2e6.jpg) :
> 
> I'd be happy to add them to the project if you need any assistance with this

@ethmtrgt Updated the issue with pull requests that fix this issue. Feel free to review

**Comment by ethmtrgt** [comment]
Hey @orama254 very well done, appreciate it... And thanks for your contribution.

I was viewing on mobile, missed the line 31 in CoC file :(

**Comment by orama254** [comment]
> Hey @orama254 very well done, appreciate it... And thanks for your contribution.
> 
> I was viewing on mobile, missed the line 31 in CoC file :(

No problem @ethmtrgt, are you ok adding it or you can send me the details and I can add it?

**Comment by ethmtrgt** [comment]
Thank you so much, can you kindly add `ethmtrgt+github@gmail.com` ?

Thanks in advance!
